# Generated by Django 5.1 on 2024-10-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(default='1950-01-01', verbose_name='Fecha de nacimiento'),
        ),
    ]
