# Generated by Django 5.1 on 2024-10-03 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_is_niño'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Niño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apoderado')),
            ],
        ),
    ]
