# Generated by Django 5.1 on 2024-10-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_apoderado_user_user_apoderado'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='is_apoderado',
            field=models.BooleanField(default=False, verbose_name='Es Apoderado'),
        ),
    ]
