# Generated by Django 5.1 on 2024-10-08 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_apoderado_is_apoderado'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='niño',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='niño', to='core.niño'),
        ),
        migrations.AlterField(
            model_name='niño',
            name='apoderado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apoderado', to='core.apoderado'),
        ),
    ]
