# Generated by Django 5.1 on 2024-10-08 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_apoderado_is_apoderado'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='niño_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='niño_asociado_al_apoderado', to='core.niño'),
        ),
        migrations.AlterField(
            model_name='niño',
            name='apoderado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apoderado_del_niño', to='core.apoderado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='apoderado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.apoderado'),
        ),
    ]
