# Generated by Django 5.1 on 2024-10-08 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_apoderado_niño_id_alter_niño_apoderado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoderado',
            name='niño_id',
        ),
        migrations.AddField(
            model_name='apoderado',
            name='niño',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='niño_asociado_al_apoderado', to='core.niño'),
        ),
    ]
