# Generated by Django 5.1 on 2024-10-08 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_apoderado_niño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='niño',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niño', to='core.niño'),
        ),
    ]
