# Generated by Django 5.1 on 2024-10-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_apoderado_niño_id_apoderado_niño'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apoderado',
            old_name='niño',
            new_name='niño_id',
        ),
        migrations.RemoveField(
            model_name='niño',
            name='id',
        ),
        migrations.AddField(
            model_name='niño',
            name='niño_id',
            field=models.AutoField(default='', primary_key=True, serialize=False, unique=True),
        ),
    ]
