# Generated by Django 5.1.2 on 2024-11-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_curso_remove_apoderado_niñodelapoderado_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(default='11.111.111-1', max_length=12, verbose_name='Rut'),
        ),
    ]
