# Generated by Django 5.1 on 2024-10-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_niño_apoderado_niño_id_remove_niño_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apoderado',
            old_name='niño_id',
            new_name='niño',
        ),
        migrations.RenameField(
            model_name='niño',
            old_name='niño_id',
            new_name='niño',
        ),
    ]
