# Generated by Django 5.1.2 on 2024-11-13 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='planificacion',
            name='nombre',
        ),
        migrations.AddField(
            model_name='planificacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='planificaciones/'),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='subido_a',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
