# Generated by Django 5.1 on 2024-10-08 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_apoderado_niño'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoderado',
            name='niño',
        ),
        migrations.AlterField(
            model_name='niño',
            name='apoderado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apoderado'),
        ),
    ]
