# Generated by Django 5.1 on 2024-10-08 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_niño_id_apoderado_niño_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='niño',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niño_asociado_al_apoderado', to='core.niño'),
        ),
    ]
