# Generated by Django 5.1.2 on 2024-11-13 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_planificacionapoderado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_niño',
        ),
    ]
