# Generated by Django 5.1.2 on 2024-11-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_user_is_niño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_apoderado',
            field=models.BooleanField(default=True, verbose_name='Es Apoderado'),
        ),
    ]
