# Generated by Django 5.1.2 on 2024-11-14 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_is_apoderado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodo_ID', models.CharField(default='2020-2021', max_length=10)),
                ('Semestre', models.CharField(max_length=3)),
                ('Calif_Parcial_1', models.CharField(max_length=3)),
                ('Calif_Parcial_2', models.CharField(max_length=3)),
                ('Calif_Parcial_3', models.CharField(max_length=3)),
                ('Curso_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('Estudiante_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
            ],
            options={
                'db_table': 'notas',
            },
        ),
    ]
