# Generated by Django 5.1.2 on 2024-11-14 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('documento', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('subido_a', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReportesApoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('documento', models.FileField(blank=True, null=True, upload_to='reportesApoderado/')),
                ('subido_a', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
