# Generated by Django 5.1.2 on 2024-11-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_reportes_reportesapoderado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='Calif_Parcial_1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Calif_Parcial_2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Calif_Parcial_3',
        ),
        migrations.AddField(
            model_name='notas',
            name='Nota',
            field=models.CharField(choices=[('L', 'Logrado'), ('NL', 'No Logrado')], default='L', max_length=2),
        ),
    ]
