# Generated by Django 5.1.2 on 2024-11-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_notas_calif_parcial_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='Nivel',
            field=models.CharField(choices=[('DFM', 'Desarrollo Físico y Motor'), ('DSE', 'Desarollo Socioemocional'), ('DCG', 'Desarrollo Cognitivo'), ('DCM', 'Desarrollo Comunicativo')], default='DFM', max_length=3),
        ),
    ]
