# Generated by Django 5.1.2 on 2024-11-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_notas_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='Sesion',
            field=models.CharField(choices=[('1', 'Una sesión'), ('2', 'Dos sesiones'), ('3', 'Tres sesiones'), ('4', 'Cuatro sesiones'), ('5', 'Cinco sesiones'), ('6', 'Seis sesiones'), ('7', 'Siete sesiones'), ('8', 'Ocho sesiones'), ('9', 'Nueve sesiones'), ('10', 'Diez sesiones')], default='10', max_length=2),
        ),
    ]
