# Generated by Django 5.1.2 on 2024-11-24 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notas_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='apoderado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='core.apoderado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(default='', max_length=12, verbose_name='Telefono'),
        ),
    ]
