# Generated by Django 4.0.6 on 2024-11-25 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_estudiante_apoderado_alter_user_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='apoderado',
        ),
    ]
