# Generated by Django 4.0.6 on 2024-11-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_estudiante_apoderado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportes',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='reportes',
            name='subido_a',
        ),
        migrations.RemoveField(
            model_name='reportesapoderado',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='reportesapoderado',
            name='subido_a',
        ),
    ]
