# Generated by Django 4.0.6 on 2024-11-27 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_reportes_documento_remove_reportes_subido_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='reportes/'),
        ),
        migrations.AddField(
            model_name='reportes',
            name='subido_a',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reportesapoderado',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='reportesApoderado/'),
        ),
        migrations.AddField(
            model_name='reportesapoderado',
            name='subido_a',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
