# Generated by Django 4.0.6 on 2024-11-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_reportes_documento_reportes_subido_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='documento',
            field=models.FileField(default='planificaciones/', upload_to='planificaciones/'),
        ),
        migrations.AlterField(
            model_name='planificacionapoderado',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='planificacionapoderado',
            name='documento',
            field=models.FileField(default='actividades/', upload_to='actividades/'),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='documento',
            field=models.FileField(default='reportes/', upload_to='reportes/'),
        ),
        migrations.AlterField(
            model_name='reportesapoderado',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reportesapoderado',
            name='documento',
            field=models.FileField(default='reportesApoderado/', upload_to='reportesApoderado/'),
        ),
    ]
