# Generated by Django 4.0.6 on 2024-11-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_planificacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['fecha'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['created'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['created'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='notas',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterModelOptions(
            name='planificacion',
            options={'verbose_name': 'Planificación de Parvularias', 'verbose_name_plural': 'Planificaciones de Parvularias'},
        ),
        migrations.AlterModelOptions(
            name='planificacionapoderado',
            options={'verbose_name': 'Reporte de Apoderados', 'verbose_name_plural': 'Reportes de Apoderados'},
        ),
        migrations.AlterModelOptions(
            name='reportes',
            options={'verbose_name': 'Reporte de Parvularias', 'verbose_name_plural': 'Reportes de Parvularias'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
