# Generated by Django 5.0 on 2024-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_asistencia_options_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_apoderado',
            field=models.BooleanField(default=False, verbose_name='Es Apoderado'),
        ),
    ]
