# Generated by Django 5.0 on 2024-11-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_user_is_apoderado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planificacionapoderado',
            options={'verbose_name': 'Planificación de Apoderados', 'verbose_name_plural': 'Planificaciones de Apoderados'},
        ),
        migrations.AlterModelOptions(
            name='reportesapoderado',
            options={'verbose_name': 'Reporte de Apoderados', 'verbose_name_plural': 'Reportes de Apoderados'},
        ),
    ]
