# Generated by Django 5.1.2 on 2024-12-05 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_planificacionapoderado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='Curso_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.curso'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Estudiante_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.estudiante'),
        ),
    ]
